language: generic
sudo: false
git:
  depth: 10

matrix:
  include:
    - os: linux
      env:
        - VIM_VERSION=v8.0.0000
        - THEMIS_PROFILE=vim-profile-v8.0.txt
    - os: linux
      env:
        - VIM_VERSION=master
        - THEMIS_PROFILE=vim-profile-master.txt

install:
  - git clone --depth 1 --branch "${VIM_VERSION}" https://github.com/vim/vim /tmp/vim
  - cd /tmp/vim
  - ./configure --prefix="${HOME}/vim" --with-features=huge --enable-fail-if-missing
  - make -j2
  - make install
  - export PATH=$HOME/vim/bin:$PATH

before_script:
  - git clone --depth 1 --branch v1.5.4 --single-branch https://github.com/thinca/vim-themis /tmp/vim-themis

script:
  - cd $TRAVIS_BUILD_DIR
  - uname -a
  - which -a vim
  - vim --cmd version --cmd quit
  - /tmp/vim-themis/bin/themis --reporter dot
